apiVersion: v1
kind: Secret
metadata:
  name: skillz-test-repository
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: https://github.com/vourteen14/shanghiang-skillz.git